# fly.toml file generated for twitch-numericajam-auth on 2023-08-15T17:19:50-04:00

app = "twitch-numericajam-auth"
kill_signal = "SIGINT"
kill_timeout = 5
# mounts = []
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[experimental]
  cmd = "node .output/server/index.mjs"